version: '2'
services:
  jenkins:
    image: 'jenkins/jenkins:latest'
    container_name: 'jenkins'
    restart: always
    ports:
      - '8100:8080'
      - '50100:50000'
    expose:
      - '8080'
      - '50000'
    volumes:
      - './jenkins_home:/var/jenkins_home'
    environment:
      TZ: "Asia/Seoul"
