version: '3.1'
services:
  db:
    image: mysql
    container_name: caru_mysql
    ports:
      - "13306:3306"
    restart: always
    volumes:
      - ./data:/var/lib/mysql 
    environment:
      - MYSQL_ROOT_PASSWORD=rudeo512
      - MYSQL_USER=caru
      - MYSQL_PASSWORD=rudeo512
      - MYSQL_DATABASE=jpa
